baseURL = "https://www.tacoda.dev/"
title = "Ian Johnson"
paginate = 5
theme = "m10c"
enableRobotsTXT = false
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Ian Johnson"
description = "Software Engineer"
keywords = [ "Blog", "Portfolio" ]
author = "Ian Johnson"
avatar = "http://gravatar.com/avatar/0a09dcb201b488dece3b9e47e3f2443b"
menu_item_separator = "|"
images = [ "http://gravatar.com/avatar/0a09dcb201b488dece3b9e47e3f2443b" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideFooter = true
hideSummary = false
showtoc = false
tocopen = false

  [params.style]
  primaryColor = "#57cc8a"
  darkColor = "#3f4c54"
  # primaryColor = "#d3908e"
  # primaryColor = "#8caee0"
  # primaryColor = "#9993dc"
  # darkestColor = "#d35050"
  # lightColor = "#f5e3e0"
  # lightestColor = "#f5f5f5"

  [params.assets]
  favicon = "favicon.ico"

  [params.label]
  text = "Ian Johnson"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [[params.social]]
  icon = "github"
  name = "github"
  url = "https://github.com/tacoda"

  [[params.social]]
  icon = "linkedin"
  name = "linkedin"
  url = "https://www.linkedin.com/in/tacoda/"

  [[params.social]]
  icon = "rss"
  name = "rss"
  url = "/posts/index.xml"

  [[params.social]]
  icon = "mail"
  name = "email"
  url = "mailto:tacoda@hey.com"

# [params.analytics.google]
# SiteVerificationTag = "XYZabc"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

  # [params.cover]
  # hidden = true
  # hiddenInList = true
  # hiddenInSingle = true

  # [params.editPost]
  # URL = "https://github.com/tacoda/tacoda.github.io/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "resources"
name = "resources"
url = "/resources/"
weight = 40

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 50

[markup.highlight]
noClasses = false

[outputs]
home = ["HTML", "RSS", "JSON"]
