baseURL = "https://tacoda.github.io/"
title = "Ian Johnson"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = false
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Ian Johnson"
description = "Ian Johnson: Software Engineer"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Ian Johnson"
images = [ "http://gravatar.com/avatar/0a09dcb201b488dece3b9e47e3f2443b" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideFooter = true
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Ian Johnson"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Ian Johnson"
  subtitle = "Software Engineer | Security Enthusiast | Open Source Contributor"
  imageUrl = "http://gravatar.com/avatar/0a09dcb201b488dece3b9e47e3f2443b"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "About"
    url = "about"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

#   [params.homeInfoParams]
#   Title = "Ian Johnson"
#   Content = """Software Engineer | Full Stack Developer | Security Enthusiast | Open Source Contributor\n\n
# I am a full stack web developer with a penchant \
# for Ruby on Rails and React. Application security \
# is something I am very focused on. Using Rust to \
# explore building native programs has been a recent \
# project of mine. I am always interested in learning \
# more about security and cloud computing. I also enjoy \
# contributing to open source projects.\
# """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/tacoda"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/tacoda/"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://hachyderm.io/@tacoda"

  [[params.socialIcons]]
  name = "discord"
  url = "https://discordapp.com/users/690011890415698169"

  [[params.socialIcons]]
  name = "matrix"
  url = "https://matrix.to/#/@tacoda:matrix.org"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:tacoda@hey.com"

  # [[params.socialIcons]]
  # name = "exercism"
  # url = "https://exercism.com/"

# [params.analytics.google]
# SiteVerificationTag = "XYZabc"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

  # [params.cover]
  # hidden = true
  # hiddenInList = true
  # hiddenInSingle = true

  # [params.editPost]
  # URL = "https://github.com/tacoda/tacoda.github.io/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

# [[menu.main]]
# identifier = "categories"
# name = "categories"
# url = "/categories/"
# weight = 10

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

# [[menu.main]]
# identifier = "Ian Johnson"
# name = "tacoda.dev"
# url = "https://www.tacoda.dev/"
# weight = 30

[markup.highlight]
noClasses = false

